travis:
  secure:
    BINSTAR_TOKEN: CJIXT2rE7vtSodA32gdoa+0Yl8v6dzE9tpDJX5elRjoDTMXACu9kbh40LcoU7p9WOicFE344ofGi4wcdZhQC+tDLi6dWB8wQ6/MKnc3wE2oLIcrkJ3t6YYkcdSuED1YEWr2+UEm2g4soWVTmLVCzKZHVFhYpzaIjxpGH3kt0ReFX3neyk2/V7n9+ClZNruxEohBYlOIJJmkvecaBD5xg1QADt09C+3JrDrc5nTOfcjTQnVgDuEdITL0u9MgxIaeHDUOoc38+paHIcC2es1Que4jhd2uxCgXcqhziplQ2yQBPhhMrJ3w20I1pCSNHPEabY5VGr8eeA3EkEjDgc/vk1+0jLyNQYtkQ+qc2Zm+QNMgQo1ndoT0he71L3OIXNiEQA6DgahgXrnbOTvmnL97wlkCvxP2JIqSg1mb/LfzCacIa/ezcNOQsTsJ+DdOog9cJZeZjyTsBLql00MxZPkNaEg7ypfydSzJZU5q/GR24lEsddwJyOSzl5qkg139qZ7WqhTsL26tolTmKcdQgN+O9CRGBsq+zM2/weVZDk9fJ/K8hCg4T5uLysDd89+xo3CSYbnSoIbqkhO9+B8eEeFE6Wt9KpUM8AETZrZjemdFDs/8oh/U3QAuexAKk09Tt36Ir92YVI12pzp6eJOibWldZ2DnNYJs9GkprHeUv8MJuvM8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
